/****************************************************************************
 * @file       XGuiConfig.h
 * @brief      XGui 模块总开关与子功能配置。
 * @details    CXinYueConfig.h 只保留 XGUI_ON 总开关入口；所有 GUI 子开关
 *             在本文件集中定义。嵌入式构建只需 -DXGUI_ON=0 即可裁剪整个
 *             XGui，同时保留各子开关名称供桌面构建做精细裁剪。
 ****************************************************************************/
#ifndef XGUICONFIG_H
#define XGUICONFIG_H

#include "CXinYueConfig.h"

#ifndef XGUI_ON
#define XGUI_ON 1
#endif

/* 图像与窗口基础模块。 */
#ifndef XIMAGECODEC_ON
#define XIMAGECODEC_ON 1
#endif
#ifndef XSCREEN_ON
#define XSCREEN_ON 1
#endif
#ifndef XSURFACEFORMAT_ON
#define XSURFACEFORMAT_ON 1
#endif
#ifndef XCURSOR_ON
#define XCURSOR_ON 1
#endif
#ifndef XWINDOW_ON
#define XWINDOW_ON 1
#endif
#ifndef XACCESSIBLE_ON
#define XACCESSIBLE_ON 1
#endif

/* 应用、样式、剪贴板与 MIME。 */
#ifndef XGUIAPPLICATION_ON
#define XGUIAPPLICATION_ON 1
#endif
#ifndef XSTYLEHINTS_ON
#define XSTYLEHINTS_ON 1
#endif
#ifndef XCLIPBOARD_ON
#define XCLIPBOARD_ON 1
#endif
#ifndef XMIMEDATA_ON
#define XMIMEDATA_ON 1
#endif
#ifndef XPALETTE_ON
#define XPALETTE_ON 1
#endif
#ifndef XIMAGEIOPLUGIN_ON
#define XIMAGEIOPLUGIN_ON 1
#endif

/* 平台集成与平台资源。 */
#ifndef XPLATFORMINTEGRATION_ON
#define XPLATFORMINTEGRATION_ON 1
#endif
#ifndef XPLATFORMNATIVEINTERFACE_ON
#define XPLATFORMNATIVEINTERFACE_ON 1
#endif
#ifndef XPLATFORMWINDOW_ON
#define XPLATFORMWINDOW_ON 1
#endif
#ifndef XPLATFORMINPUTCTX_ON
#define XPLATFORMINPUTCTX_ON 1
#endif
#ifndef XBACKINGSTORE_ON
#define XBACKINGSTORE_ON 1
#endif
#ifndef XPLATFORMBACKINGSTORE_ON
#define XPLATFORMBACKINGSTORE_ON 1
#endif

/* 后备存储渲染模式（参考 LVGL 9 的 PARTIAL/DIRECT/FULL）。
 * PARTIAL：使用小块 tile buffer，逐片绘制并提交；DIRECT：整屏双缓冲，
 * 绘制脏区后交换；FULL：每次绘制并提交整屏。 */
#define XGUI_BACKINGSTORE_RENDER_MODE_PARTIAL 0
#define XGUI_BACKINGSTORE_RENDER_MODE_DIRECT  1
#define XGUI_BACKINGSTORE_RENDER_MODE_FULL    2
#ifndef XGUI_BACKINGSTORE_RENDER_MODE
#if defined(_WIN32)
/* Win32 desktop follows the LVGL Windows simulator: a persistent full-size
 * framebuffer is rendered directly and submitted once per frame. Embedded
 * targets can override this to PARTIAL at compile time. */
#define XGUI_BACKINGSTORE_RENDER_MODE XGUI_BACKINGSTORE_RENDER_MODE_DIRECT
#else
#define XGUI_BACKINGSTORE_RENDER_MODE XGUI_BACKINGSTORE_RENDER_MODE_PARTIAL
#endif
#endif

/* DIRECT/FULL 模式使用的整屏缓冲数量；至少 1，DIRECT 推荐 2。 */
#ifndef XGUI_BACKINGSTORE_BUFFER_COUNT
#if defined(_WIN32)
#define XGUI_BACKINGSTORE_BUFFER_COUNT 2
#else
#define XGUI_BACKINGSTORE_BUFFER_COUNT 1
#endif
#endif

/* PARTIAL 每块绘制缓冲的最大尺寸。窗口边缘的最后一块会按窗口尺寸
 * 裁剪，但缓冲按此上限分配，避免每片重复重建 XImage 描述。 */
#ifndef XGUI_BACKINGSTORE_PARTIAL_BUFFER_WIDTH
#define XGUI_BACKINGSTORE_PARTIAL_BUFFER_WIDTH 160
#endif
#ifndef XGUI_BACKINGSTORE_PARTIAL_BUFFER_HEIGHT
#define XGUI_BACKINGSTORE_PARTIAL_BUFFER_HEIGHT 80
#endif

/* 可选的平台启动帧缓冲。应用或板级配置可以在编译选项中把这三个
 * 宏替换为静态显存地址和容量；平台后端创建 XPlatformBackingStore
 * 时只登记一次，后续 resize 只重建 XImage 描述，不重复绑定缓冲。
 * 默认值为 0，表示由平台后端按需从内部内存分配。 */
#ifndef XGUI_BACKINGSTORE_BUFFER1
#define XGUI_BACKINGSTORE_BUFFER1 0
#endif
#ifndef XGUI_BACKINGSTORE_BUFFER2
#define XGUI_BACKINGSTORE_BUFFER2 0
#endif
#ifndef XGUI_BACKINGSTORE_BUFFER_SIZE
#define XGUI_BACKINGSTORE_BUFFER_SIZE 0
#endif

#if XGUI_BACKINGSTORE_RENDER_MODE < XGUI_BACKINGSTORE_RENDER_MODE_PARTIAL || \
    XGUI_BACKINGSTORE_RENDER_MODE > XGUI_BACKINGSTORE_RENDER_MODE_FULL
#undef XGUI_BACKINGSTORE_RENDER_MODE
#define XGUI_BACKINGSTORE_RENDER_MODE XGUI_BACKINGSTORE_RENDER_MODE_PARTIAL
#endif
#if XGUI_BACKINGSTORE_BUFFER_COUNT < 1
#undef XGUI_BACKINGSTORE_BUFFER_COUNT
#define XGUI_BACKINGSTORE_BUFFER_COUNT 1
#endif
#if XGUI_BACKINGSTORE_BUFFER_COUNT > 2
/* 当前后备存储实现支持单缓冲或双缓冲；更大的值会造成配置与实际
 * 存储数量不一致，因此统一收敛到双缓冲。 */
#undef XGUI_BACKINGSTORE_BUFFER_COUNT
#define XGUI_BACKINGSTORE_BUFFER_COUNT 2
#endif
#if XGUI_BACKINGSTORE_PARTIAL_BUFFER_WIDTH < 1
#undef XGUI_BACKINGSTORE_PARTIAL_BUFFER_WIDTH
#define XGUI_BACKINGSTORE_PARTIAL_BUFFER_WIDTH 1
#endif
#if XGUI_BACKINGSTORE_PARTIAL_BUFFER_HEIGHT < 1
#undef XGUI_BACKINGSTORE_PARTIAL_BUFFER_HEIGHT
#define XGUI_BACKINGSTORE_PARTIAL_BUFFER_HEIGHT 1
#endif
#if XGUI_BACKINGSTORE_RENDER_MODE == XGUI_BACKINGSTORE_RENDER_MODE_DIRECT && \
    XGUI_BACKINGSTORE_BUFFER_COUNT < 2
#undef XGUI_BACKINGSTORE_BUFFER_COUNT
#define XGUI_BACKINGSTORE_BUFFER_COUNT 2
#endif

/* 绘图与窗口基础模块。 */
#ifndef XPAINTER_ON
#define XPAINTER_ON 1
#endif
#ifndef XPAINTER_SHAPE_ON
#define XPAINTER_SHAPE_ON 1
#endif
#ifndef XPAINTER_POLYGON_ON
#define XPAINTER_POLYGON_ON 1
#endif
#ifndef XPAINTER_PENSTYLE_ON
#define XPAINTER_PENSTYLE_ON 1
#endif
#ifndef XPAINTER_BRUSH_ON
#define XPAINTER_BRUSH_ON 1
#endif
#ifndef XPAINTER_BRUSH_ORIGIN_ON
#define XPAINTER_BRUSH_ORIGIN_ON 1
#endif
#ifndef XPAINTER_BACKGROUND_ON
#define XPAINTER_BACKGROUND_ON 1
#endif
#ifndef XPAINTER_PIXMAP_ON
#define XPAINTER_PIXMAP_ON 1
#endif
#ifndef XPAINTER_IMAGE_RECT_ON
#define XPAINTER_IMAGE_RECT_ON 1
#endif
#ifndef XPAINTER_TILED_PIXMAP_ON
#define XPAINTER_TILED_PIXMAP_ON 1
#endif
#ifndef XPAINTER_PATH_ON
#define XPAINTER_PATH_ON 1
#endif
#ifndef XPAINTER_TEXTLAYOUT_ON
#define XPAINTER_TEXTLAYOUT_ON 1
#endif
#ifndef XPAINTER_LAYOUT_DIRECTION_ON
#define XPAINTER_LAYOUT_DIRECTION_ON 1
#endif
#ifndef XPAINTER_RENDERHINT_ON
#define XPAINTER_RENDERHINT_ON 1
#endif
#ifndef XPAINTER_WORLD_MATRIX_ON
#define XPAINTER_WORLD_MATRIX_ON 1
#endif
#ifndef XPAINTER_VIEW_TRANSFORM_ON
#define XPAINTER_VIEW_TRANSFORM_ON 1
#endif
#ifndef XPAINTER_CLIP_ON
#define XPAINTER_CLIP_ON 1
#endif
#ifndef XPAINTER_CLIP_REGION_ON
#define XPAINTER_CLIP_REGION_ON 1
#endif

/* 控件、布局、输入法与窗口事件。 */
#ifndef XAPPLICATION_ON
#define XAPPLICATION_ON 1
#endif
#ifndef XWIDGET_ON
#define XWIDGET_ON 1
#endif
#ifndef XFRAME_ON
#define XFRAME_ON 1
#endif
#ifndef XLABEL_ON
#define XLABEL_ON 1
#endif
#ifndef XPUSHBUTTON_ON
#define XPUSHBUTTON_ON 1
#endif
#ifndef XLAYOUT_ON
#define XLAYOUT_ON 1
#endif
#ifndef XLAYOUT_STACKED_ON
#define XLAYOUT_STACKED_ON 1
#endif
#ifndef XINPUTMETHOD_ON
#define XINPUTMETHOD_ON 1
#endif
#ifndef XWINDOWEVENT_ON
#define XWINDOWEVENT_ON 1
#endif
#ifndef XWINDOWSYSTEMINTERFACE_ON
#define XWINDOWSYSTEMINTERFACE_ON 1
#endif

/* 性能悬浮层（基于 XLabel，供 demo 和平台验收使用）。桌面默认开启，
 * 嵌入式可通过 -DXGUI_PERFORMANCE_OVERLAY_ON=0 完全裁剪；各项指标也可
 * 独立关闭，避免引入不需要的格式化和采样开销。 */
#ifndef XGUI_PERFORMANCE_OVERLAY_ON
#if defined(_WIN32) || defined(__linux__) || defined(__APPLE__)
#define XGUI_PERFORMANCE_OVERLAY_ON 1
#else
#define XGUI_PERFORMANCE_OVERLAY_ON 0
#endif
#endif
#ifndef XGUI_PERFORMANCE_OVERLAY_FPS_ON
#define XGUI_PERFORMANCE_OVERLAY_FPS_ON 1
#endif
#ifndef XGUI_PERFORMANCE_OVERLAY_FRAME_TIME_ON
#define XGUI_PERFORMANCE_OVERLAY_FRAME_TIME_ON 1
#endif
#ifndef XGUI_PERFORMANCE_OVERLAY_NETWORK_ON
#define XGUI_PERFORMANCE_OVERLAY_NETWORK_ON 1
#endif
#ifndef XGUI_PERFORMANCE_OVERLAY_UPDATE_MS
#define XGUI_PERFORMANCE_OVERLAY_UPDATE_MS 250
#endif

/* 原生窗口与系统无障碍平台后端。 */
#ifndef XPLATFORMNATIVEWINDOW_ON
#define XPLATFORMNATIVEWINDOW_ON 1
#endif
#ifndef XPLATFORMNATIVEWINDOW_X11_ON
#define XPLATFORMNATIVEWINDOW_X11_ON 1
#endif
#ifndef XPLATFORMNATIVEWINDOW_WIN32_ON
#define XPLATFORMNATIVEWINDOW_WIN32_ON 1
#endif
#ifndef XPLATFORMACCESSIBILITY_ATSPI_ON
#define XPLATFORMACCESSIBILITY_ATSPI_ON 1
#endif
#ifndef XPLATFORMACCESSIBILITY_UIA_ON
#define XPLATFORMACCESSIBILITY_UIA_ON 1
#endif

/* 保留原有模块依赖：布局和控件级应用不能脱离其承载对象单独存在。 */
#if !XWIDGET_ON || !XGUIAPPLICATION_ON || !XWINDOW_ON
#undef XLAYOUT_ON
#define XLAYOUT_ON 0
#undef XFRAME_ON
#define XFRAME_ON 0
#undef XLABEL_ON
#define XLABEL_ON 0
#undef XPUSHBUTTON_ON
#define XPUSHBUTTON_ON 0
#endif
#if !XFRAME_ON
#undef XLABEL_ON
#define XLABEL_ON 0
#endif
#if !XGUIAPPLICATION_ON
#undef XAPPLICATION_ON
#define XAPPLICATION_ON 0
#endif

/* XGui 总开关关闭时，所有 GUI 子模块统一裁剪。 */
#if !XGUI_ON
#undef XIMAGECODEC_ON
#define XIMAGECODEC_ON 0
#undef XSCREEN_ON
#define XSCREEN_ON 0
#undef XSURFACEFORMAT_ON
#define XSURFACEFORMAT_ON 0
#undef XCURSOR_ON
#define XCURSOR_ON 0
#undef XWINDOW_ON
#define XWINDOW_ON 0
#undef XACCESSIBLE_ON
#define XACCESSIBLE_ON 0
#undef XGUIAPPLICATION_ON
#define XGUIAPPLICATION_ON 0
#undef XSTYLEHINTS_ON
#define XSTYLEHINTS_ON 0
#undef XCLIPBOARD_ON
#define XCLIPBOARD_ON 0
#undef XMIMEDATA_ON
#define XMIMEDATA_ON 0
#undef XPALETTE_ON
#define XPALETTE_ON 0
#undef XIMAGEIOPLUGIN_ON
#define XIMAGEIOPLUGIN_ON 0
#undef XPLATFORMINTEGRATION_ON
#define XPLATFORMINTEGRATION_ON 0
#undef XPLATFORMNATIVEINTERFACE_ON
#define XPLATFORMNATIVEINTERFACE_ON 0
#undef XPLATFORMWINDOW_ON
#define XPLATFORMWINDOW_ON 0
#undef XPLATFORMINPUTCTX_ON
#define XPLATFORMINPUTCTX_ON 0
#undef XBACKINGSTORE_ON
#define XBACKINGSTORE_ON 0
#undef XPLATFORMBACKINGSTORE_ON
#define XPLATFORMBACKINGSTORE_ON 0
#undef XGUI_BACKINGSTORE_RENDER_MODE
#define XGUI_BACKINGSTORE_RENDER_MODE XGUI_BACKINGSTORE_RENDER_MODE_PARTIAL
#undef XGUI_BACKINGSTORE_BUFFER_COUNT
#define XGUI_BACKINGSTORE_BUFFER_COUNT 1
#undef XGUI_BACKINGSTORE_BUFFER1
#define XGUI_BACKINGSTORE_BUFFER1 0
#undef XGUI_BACKINGSTORE_BUFFER2
#define XGUI_BACKINGSTORE_BUFFER2 0
#undef XGUI_BACKINGSTORE_BUFFER_SIZE
#define XGUI_BACKINGSTORE_BUFFER_SIZE 0
#undef XAPPLICATION_ON
#define XAPPLICATION_ON 0
#undef XWIDGET_ON
#define XWIDGET_ON 0
#undef XFRAME_ON
#define XFRAME_ON 0
#undef XLABEL_ON
#define XLABEL_ON 0
#undef XPUSHBUTTON_ON
#define XPUSHBUTTON_ON 0
#undef XLAYOUT_ON
#define XLAYOUT_ON 0
#undef XINPUTMETHOD_ON
#define XINPUTMETHOD_ON 0
#undef XWINDOWEVENT_ON
#define XWINDOWEVENT_ON 0
#undef XWINDOWSYSTEMINTERFACE_ON
#define XWINDOWSYSTEMINTERFACE_ON 0
#undef XGUI_PERFORMANCE_OVERLAY_ON
#define XGUI_PERFORMANCE_OVERLAY_ON 0
#undef XGUI_PERFORMANCE_OVERLAY_FPS_ON
#define XGUI_PERFORMANCE_OVERLAY_FPS_ON 0
#undef XGUI_PERFORMANCE_OVERLAY_FRAME_TIME_ON
#define XGUI_PERFORMANCE_OVERLAY_FRAME_TIME_ON 0
#undef XGUI_PERFORMANCE_OVERLAY_NETWORK_ON
#define XGUI_PERFORMANCE_OVERLAY_NETWORK_ON 0
#undef XPLATFORMNATIVEWINDOW_ON
#define XPLATFORMNATIVEWINDOW_ON 0
#undef XPLATFORMNATIVEWINDOW_X11_ON
#define XPLATFORMNATIVEWINDOW_X11_ON 0
#undef XPLATFORMNATIVEWINDOW_WIN32_ON
#define XPLATFORMNATIVEWINDOW_WIN32_ON 0
#undef XPLATFORMACCESSIBILITY_ATSPI_ON
#define XPLATFORMACCESSIBILITY_ATSPI_ON 0
#undef XPLATFORMACCESSIBILITY_UIA_ON
#define XPLATFORMACCESSIBILITY_UIA_ON 0
#endif

#include "Graphics/XImageCodec/XImageCodec_config.h"

#endif /* XGUICONFIG_H */
