/**
 * @file       XNetworkRequest.h
 * - @brief      QNetworkRequest 兼容命名入口。
 * - @details    XNetworkRequest 是 XHttpRequest 的 Qt 对齐名称别名，所有对象和内存
 *             所有权规则与 XHttpRequest 完全相同。
 */

#ifndef XNETWORKREQUEST_H
#define XNETWORKREQUEST_H
#include "XHttp_config.h"

#include "XHttpRequest.h"
#if XPROTOCOL_ON
#if XHTTP_ON

/** @brief Qt QNetworkRequest 的 XinYueC 类型别名。 */
typedef XHttpRequest XNetworkRequest;
/** @brief Qt QNetworkRequest 方法枚举别名。 */
typedef XHttpRequest_Method XNetworkRequest_Method;
/** @brief Qt QNetworkRequest 优先级枚举别名。 */
typedef XHttpRequest_Priority XNetworkRequest_Priority;
/** @brief Qt QNetworkRequest 重定向策略枚举别名。 */
typedef XHttpRequest_RedirectPolicy XNetworkRequest_RedirectPolicy;

#define XNetworkRequest_Head XHttpRequest_Head
#define XNetworkRequest_Get XHttpRequest_Get
#define XNetworkRequest_Post XHttpRequest_Post
#define XNetworkRequest_Put XHttpRequest_Put
#define XNetworkRequest_Delete XHttpRequest_Delete
#define XNetworkRequest_Patch XHttpRequest_Patch
#define XNetworkRequest_Custom XHttpRequest_Custom
#define XNetworkRequest_HighPriority XHttpRequest_HighPriority
#define XNetworkRequest_NormalPriority XHttpRequest_NormalPriority
#define XNetworkRequest_LowPriority XHttpRequest_LowPriority
#define XNetworkRequest_ManualRedirectPolicy XHttpRequest_ManualRedirectPolicy
#define XNetworkRequest_NoLessSafeRedirectPolicy XHttpRequest_NoLessSafeRedirectPolicy
#define XNetworkRequest_SameOriginRedirectPolicy XHttpRequest_SameOriginRedirectPolicy
#define XNetworkRequest_UserVerifiedRedirectPolicy XHttpRequest_UserVerifiedRedirectPolicy

#define XNetworkRequest_class_init XHttpRequest_class_init
#define XNetworkRequest_init XHttpRequest_init
#define XNetworkRequest_create XHttpRequest_create
#define XNetworkRequest_create_url XHttpRequest_create_url
#define XNetworkRequest_create_copy XHttpRequest_create_copy
#define XNetworkRequest_create_move XHttpRequest_create_move
#define XNetworkRequest_deinit_base XHttpRequest_deinit_base
#define XNetworkRequest_delete_base XHttpRequest_delete_base
#define XNetworkRequest_url_const XHttpRequest_url_const
#define XNetworkRequest_setUrl XHttpRequest_setUrl
#define XNetworkRequest_setUrl_utf8 XHttpRequest_setUrl_utf8
#define XNetworkRequest_headers_const XHttpRequest_headers_const
#define XNetworkRequest_headers XHttpRequest_headers
#define XNetworkRequest_setRawHeader XHttpRequest_setRawHeader
#define XNetworkRequest_hasRawHeader XHttpRequest_hasRawHeader
#define XNetworkRequest_rawHeader XHttpRequest_rawHeader
#define XNetworkRequest_rawHeaderList XHttpRequest_rawHeaderList
#define XNetworkRequest_setHeaderKnown XHttpRequest_setHeaderKnown
#define XNetworkRequest_headerKnown XHttpRequest_headerKnown
#define XNetworkRequest_http1Configuration_const XHttpRequest_http1Configuration_const
#define XNetworkRequest_setHttp1Configuration XHttpRequest_setHttp1Configuration
#define XNetworkRequest_http2Configuration_const XHttpRequest_http2Configuration_const
#define XNetworkRequest_setHttp2Configuration XHttpRequest_setHttp2Configuration
#define XNetworkRequest_body_const XHttpRequest_body_const
#define XNetworkRequest_setBody XHttpRequest_setBody
#define XNetworkRequest_setBody_utf8 XHttpRequest_setBody_utf8
#define XNetworkRequest_setMethod XHttpRequest_setMethod
#define XNetworkRequest_setCustomMethod XHttpRequest_setCustomMethod
#define XNetworkRequest_setCustomMethod_bytes XHttpRequest_setCustomMethod_bytes
#define XNetworkRequest_method XHttpRequest_method
#define XNetworkRequest_customMethod_const XHttpRequest_customMethod_const
#define XNetworkRequest_setPriority XHttpRequest_setPriority
#define XNetworkRequest_priority XHttpRequest_priority
#define XNetworkRequest_setRedirectPolicy XHttpRequest_setRedirectPolicy
#define XNetworkRequest_redirectPolicy XHttpRequest_redirectPolicy
#define XNetworkRequest_setMaximumRedirectsAllowed XHttpRequest_setMaximumRedirectsAllowed
#define XNetworkRequest_maximumRedirectsAllowed XHttpRequest_maximumRedirectsAllowed
#define XNetworkRequest_setTransferTimeout XHttpRequest_setTransferTimeout
#define XNetworkRequest_transferTimeout XHttpRequest_transferTimeout
#define XNetworkRequest_setAutoDecompress XHttpRequest_setAutoDecompress
#define XNetworkRequest_autoDecompress XHttpRequest_autoDecompress
#define XNetworkRequest_setAttribute XHttpRequest_setAttribute
#define XNetworkRequest_attribute XHttpRequest_attribute
#define XNetworkRequest_clearAttribute XHttpRequest_clearAttribute
#define XNetworkRequest_clearAttributes XHttpRequest_clearAttributes
#define XNetworkRequest_toHttp1 XHttpRequest_toHttp1

#endif // XHTTP_ON
#endif /* XPROTOCOL_ON */
#endif /* XNETWORKREQUEST_H */
