/** @file XCryptographic_config.h
 * @brief XCryptographic 通用算法裁剪配置。
 */

#ifndef XCRYPTOGRAPHIC_CONFIG_H
#define XCRYPTOGRAPHIC_CONFIG_H

#include "XMemory.h"

/**
 * @brief XCryptographicHash 使用的内存池类型。
 * @details 控制哈希模块拥有的动态内存的分配来源，包括哈希上下文、
 *          输入缓存、resultView 缓存以及 HMAC 内外层哈希上下文；同时
 *          控制 XCryptographic.c 中 HKDF/PBKDF2/TLS-PRF 的临时工作区。
 *          HMAC 的固定尺寸工作区使用栈内存，不进行系统堆分配。
 *          返回的 XByteArray 对象仍遵循 XByteArray 自身的分配策略。
 *          默认的 XMEMORY_TYPE_HYBRID 会按 XMemory 的规则将大块内存回退到
 *          系统分配器；若要求 Hash 工作区完全来自多池，应显式配置为
 *          XMEMORY_TYPE_MULTIPOOL。
 *          可配置为 XMEMORY_TYPE_SYSTEM、XMEMORY_TYPE_MULTIPOOL 或
 *          XMEMORY_TYPE_HYBRID。
 */
#ifndef XCRYPTOGRAPHIC_HASH_MEMORY_POOL_TYPE
#define XCRYPTOGRAPHIC_HASH_MEMORY_POOL_TYPE XMEMORY_TYPE_HYBRID
#endif

/** @brief 启用 SHA-256 摘要算法。 */
#ifndef XCRYPTOGRAPHIC_SHA256_ON
#define XCRYPTOGRAPHIC_SHA256_ON 1
#endif

/** @brief 启用 HMAC-SHA-256 消息认证码算法。 */
#ifndef XCRYPTOGRAPHIC_HMAC_SHA256_ON
#define XCRYPTOGRAPHIC_HMAC_SHA256_ON XCRYPTOGRAPHIC_SHA256_ON
#endif

/** @brief 启用 RIPEMD-160 摘要算法。 */
#ifndef XCRYPTOGRAPHIC_RIPEMD160_ON
#define XCRYPTOGRAPHIC_RIPEMD160_ON 1
#endif

/** @brief 启用基于 SHA-256 的 PBKDF2 密钥派生算法。 */
#ifndef XCRYPTOGRAPHIC_PBKDF2_HMAC_SHA256_ON
#define XCRYPTOGRAPHIC_PBKDF2_HMAC_SHA256_ON XCRYPTOGRAPHIC_HMAC_SHA256_ON
#endif

/** @brief 启用基于已支持 HMAC 摘要的 PBKDF2 密钥派生算法。 */
#ifndef XCRYPTOGRAPHIC_PBKDF2_HMAC_ON
#define XCRYPTOGRAPHIC_PBKDF2_HMAC_ON 1
#endif

/** @brief 启用 AES-128-CTR。 */
#ifndef XCRYPTOGRAPHIC_AES128_CTR_ON
#define XCRYPTOGRAPHIC_AES128_CTR_ON 1
#endif

/** @brief 启用 AES-192-CTR。 */
#ifndef XCRYPTOGRAPHIC_AES192_CTR_ON
#define XCRYPTOGRAPHIC_AES192_CTR_ON 1
#endif

/** @brief 启用 AES-256-CTR。 */
#ifndef XCRYPTOGRAPHIC_AES256_CTR_ON
#define XCRYPTOGRAPHIC_AES256_CTR_ON 1
#endif

/** @brief 启用 AES-128/192/256 ECB 无填充。 */
#ifndef XCRYPTOGRAPHIC_AES128_ECB_ON
#define XCRYPTOGRAPHIC_AES128_ECB_ON 1
#endif
#ifndef XCRYPTOGRAPHIC_AES192_ECB_ON
#define XCRYPTOGRAPHIC_AES192_ECB_ON 1
#endif
#ifndef XCRYPTOGRAPHIC_AES256_ECB_ON
#define XCRYPTOGRAPHIC_AES256_ECB_ON 1
#endif

/** @brief 启用 AES-128/192/256 CBC 无填充。 */
#ifndef XCRYPTOGRAPHIC_AES128_CBC_ON
#define XCRYPTOGRAPHIC_AES128_CBC_ON 1
#endif
#ifndef XCRYPTOGRAPHIC_AES192_CBC_ON
#define XCRYPTOGRAPHIC_AES192_CBC_ON 1
#endif
#ifndef XCRYPTOGRAPHIC_AES256_CBC_ON
#define XCRYPTOGRAPHIC_AES256_CBC_ON 1
#endif

/** @brief 启用 AES-128/192/256 CFB。 */
#ifndef XCRYPTOGRAPHIC_AES128_CFB_ON
#define XCRYPTOGRAPHIC_AES128_CFB_ON 1
#endif
#ifndef XCRYPTOGRAPHIC_AES192_CFB_ON
#define XCRYPTOGRAPHIC_AES192_CFB_ON 1
#endif
#ifndef XCRYPTOGRAPHIC_AES256_CFB_ON
#define XCRYPTOGRAPHIC_AES256_CFB_ON 1
#endif

/** @brief 启用 AES-128/192/256 OFB。 */
#ifndef XCRYPTOGRAPHIC_AES128_OFB_ON
#define XCRYPTOGRAPHIC_AES128_OFB_ON 1
#endif
#ifndef XCRYPTOGRAPHIC_AES192_OFB_ON
#define XCRYPTOGRAPHIC_AES192_OFB_ON 1
#endif
#ifndef XCRYPTOGRAPHIC_AES256_OFB_ON
#define XCRYPTOGRAPHIC_AES256_OFB_ON 1
#endif

/** @brief 启用 AES-128-CMAC。 */
#ifndef XCRYPTOGRAPHIC_AES128_CMAC_ON
#define XCRYPTOGRAPHIC_AES128_CMAC_ON 1
#endif

/** @brief 启用 AES-192-CMAC。 */
#ifndef XCRYPTOGRAPHIC_AES192_CMAC_ON
#define XCRYPTOGRAPHIC_AES192_CMAC_ON 1
#endif

/** @brief 启用 AES-256-CMAC。 */
#ifndef XCRYPTOGRAPHIC_AES256_CMAC_ON
#define XCRYPTOGRAPHIC_AES256_CMAC_ON 1
#endif

/** @brief 启用 AES-128-GCM 认证加密算法。 */
#ifndef XCRYPTOGRAPHIC_AES128_GCM_ON
#define XCRYPTOGRAPHIC_AES128_GCM_ON 1
#endif

/** @brief 启用 AES-192-GCM 认证加密算法。 */
#ifndef XCRYPTOGRAPHIC_AES192_GCM_ON
#define XCRYPTOGRAPHIC_AES192_GCM_ON 1
#endif

/** @brief 启用 AES-256-GCM 认证加密算法。 */
#ifndef XCRYPTOGRAPHIC_AES256_GCM_ON
#define XCRYPTOGRAPHIC_AES256_GCM_ON 1
#endif

/** @brief 启用 AES-128-CCM 认证加密算法。 */
#ifndef XCRYPTOGRAPHIC_AES128_CCM_ON
#define XCRYPTOGRAPHIC_AES128_CCM_ON 1
#endif

/** @brief 启用 AES-192-CCM 认证加密算法。 */
#ifndef XCRYPTOGRAPHIC_AES192_CCM_ON
#define XCRYPTOGRAPHIC_AES192_CCM_ON 1
#endif

/** @brief 启用 AES-256-CCM 认证加密算法。 */
#ifndef XCRYPTOGRAPHIC_AES256_CCM_ON
#define XCRYPTOGRAPHIC_AES256_CCM_ON 1
#endif

/** @brief 启用基于 SHA-256 的 HKDF 密钥派生算法。 */
#ifndef XCRYPTOGRAPHIC_HKDF_SHA256_ON
#define XCRYPTOGRAPHIC_HKDF_SHA256_ON XCRYPTOGRAPHIC_SHA256_ON
#endif

/** @brief 启用基于已支持 HMAC 摘要的 HKDF（RFC 5869）。 */
#ifndef XCRYPTOGRAPHIC_HKDF_HMAC_ON
#define XCRYPTOGRAPHIC_HKDF_HMAC_ON 1
#endif

/** @brief 启用 ChaCha20-Poly1305 认证加密算法。 */
#ifndef XCRYPTOGRAPHIC_CHACHA20_POLY1305_ON
#define XCRYPTOGRAPHIC_CHACHA20_POLY1305_ON 1
#endif

/** @brief 启用 ChaCha20 原始流密码。 */
#ifndef XCRYPTOGRAPHIC_CHACHA20_ON
#define XCRYPTOGRAPHIC_CHACHA20_ON XCRYPTOGRAPHIC_CHACHA20_POLY1305_ON
#endif

/** @brief 启用 X25519 密钥协商。 */
#ifndef XCRYPTOGRAPHIC_X25519_ON
#define XCRYPTOGRAPHIC_X25519_ON 1
#endif

/** @brief 启用 NIST P-256 ECDH 密钥协商。 */
#ifndef XCRYPTOGRAPHIC_ECDH_NISTP256_ON
#define XCRYPTOGRAPHIC_ECDH_NISTP256_ON 1
#endif

/** @brief 启用 NIST P-256 ECDSA 签名与验签。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_NISTP256_ON
#define XCRYPTOGRAPHIC_ECDSA_NISTP256_ON 1
#endif

/** @brief 启用 NIST P-256 确定性 ECDSA（RFC 6979）。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_NISTP256_ON
#define XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_NISTP256_ON XCRYPTOGRAPHIC_ECDSA_NISTP256_ON
#endif

/** @brief 启用 NIST P-384 ECDSA 签名与验签。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_NISTP384_ON
#define XCRYPTOGRAPHIC_ECDSA_NISTP384_ON XCRYPTOGRAPHIC_ECC_SECP384R1_ON
#endif

/** @brief 启用 NIST P-384 确定性 ECDSA（RFC 6979，SHA-384）。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_NISTP384_ON
#define XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_NISTP384_ON XCRYPTOGRAPHIC_ECDSA_NISTP384_ON
#endif

/** @brief 启用 secp256k1 ECDSA 签名与验签。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_SECP256K1_ON
#define XCRYPTOGRAPHIC_ECDSA_SECP256K1_ON XCRYPTOGRAPHIC_ECC_SECP256K1_ON
#endif

/** @brief 启用 secp256k1 确定性 ECDSA（RFC 6979）。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_SECP256K1_ON
#define XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_SECP256K1_ON XCRYPTOGRAPHIC_ECDSA_SECP256K1_ON
#endif

/** @brief 启用基于 secp256r1/SHA-256 的 ECJPAKE 密码认证密钥交换。 */
#ifndef XCRYPTOGRAPHIC_ECJPAKE_ON
#define XCRYPTOGRAPHIC_ECJPAKE_ON \
    (XCRYPTOGRAPHIC_ECDH_NISTP256_ON && XCRYPTOGRAPHIC_SHA256_ON)
#endif

/** @brief 启用 SHAKE128/256 可扩展输出函数（XOF）。 */
#ifndef XCRYPTOGRAPHIC_SHAKE_ON
#define XCRYPTOGRAPHIC_SHAKE_ON 1
#endif

/** @brief 启用 AES-128/192/256 CBC-PKCS7 填充。 */
#ifndef XCRYPTOGRAPHIC_AES128_CBC_PKCS7_ON
#define XCRYPTOGRAPHIC_AES128_CBC_PKCS7_ON 1
#endif
#ifndef XCRYPTOGRAPHIC_AES192_CBC_PKCS7_ON
#define XCRYPTOGRAPHIC_AES192_CBC_PKCS7_ON 1
#endif
#ifndef XCRYPTOGRAPHIC_AES256_CBC_PKCS7_ON
#define XCRYPTOGRAPHIC_AES256_CBC_PKCS7_ON 1
#endif

/** @brief 启用 AES-XTS（AES-128-XTS 使用 256 位组合密钥）。 */
#ifndef XCRYPTOGRAPHIC_AES128_XTS_ON
#define XCRYPTOGRAPHIC_AES128_XTS_ON 1
#endif

/** @brief 启用 AES-256-XTS 使用 512 位组合密钥。 */
#ifndef XCRYPTOGRAPHIC_AES256_XTS_ON
#define XCRYPTOGRAPHIC_AES256_XTS_ON 1
#endif

/** @brief 启用 LMS/LM-OTS（RFC 8554）签名验证。 */
#ifndef XCRYPTOGRAPHIC_LMS_ON
#define XCRYPTOGRAPHIC_LMS_ON 1
#endif

/** @brief 启用 ML-DSA-87（FIPS 204）可选原语。 */
#ifndef XCRYPTOGRAPHIC_MLDSA87_ON
#define XCRYPTOGRAPHIC_MLDSA87_ON 0
#endif

/** @brief 启用基于 SHA-256 的 HKDF 提取阶段（RFC 5869）。 */
#ifndef XCRYPTOGRAPHIC_HKDF_EXTRACT_SHA256_ON
#define XCRYPTOGRAPHIC_HKDF_EXTRACT_SHA256_ON XCRYPTOGRAPHIC_HKDF_SHA256_ON
#endif

/** @brief 启用基于 SHA-256 的 HKDF 展开阶段（RFC 5869）。 */
#ifndef XCRYPTOGRAPHIC_HKDF_EXPAND_SHA256_ON
#define XCRYPTOGRAPHIC_HKDF_EXPAND_SHA256_ON XCRYPTOGRAPHIC_HKDF_SHA256_ON
#endif

/** @brief 启用基于 SHA-256 的 TLS 1.2 PRF（RFC 5246）。 */
#ifndef XCRYPTOGRAPHIC_TLS12_PRF_SHA256_ON
#define XCRYPTOGRAPHIC_TLS12_PRF_SHA256_ON XCRYPTOGRAPHIC_HMAC_SHA256_ON
#endif

/** @brief 启用基于已支持 HMAC 摘要的 TLS 1.2 PRF（RFC 5246）。 */
#ifndef XCRYPTOGRAPHIC_TLS12_PRF_HMAC_ON
#define XCRYPTOGRAPHIC_TLS12_PRF_HMAC_ON 1
#endif

/** @brief 启用基于 SHA-256 的 TLS 1.2 PSK-to-MS（RFC 4279）。 */
#ifndef XCRYPTOGRAPHIC_TLS12_PSK_TO_MS_SHA256_ON
#define XCRYPTOGRAPHIC_TLS12_PSK_TO_MS_SHA256_ON XCRYPTOGRAPHIC_TLS12_PRF_SHA256_ON
#endif

/** @brief 启用基于已支持 HMAC 摘要的 TLS 1.2 PSK-to-MS（RFC 4279）。 */
#ifndef XCRYPTOGRAPHIC_TLS12_PSK_TO_MS_HMAC_ON
#define XCRYPTOGRAPHIC_TLS12_PSK_TO_MS_HMAC_ON XCRYPTOGRAPHIC_TLS12_PRF_HMAC_ON
#endif

/** @brief 启用基于 AES-CMAC-PRF-128 的 PBKDF2（RFC 4615）。 */
#ifndef XCRYPTOGRAPHIC_PBKDF2_AES_CMAC_PRF_128_ON
#define XCRYPTOGRAPHIC_PBKDF2_AES_CMAC_PRF_128_ON XCRYPTOGRAPHIC_AES128_CMAC_ON
#endif

/** @brief 启用 ARIA 分组密码（128/192/256 位密钥）。 */
#ifndef XCRYPTOGRAPHIC_ARIA_ON
#define XCRYPTOGRAPHIC_ARIA_ON 1
#endif

/** @brief 启用 Camellia 分组密码（128/192/256 位密钥）。 */
#ifndef XCRYPTOGRAPHIC_CAMELLIA_ON
#define XCRYPTOGRAPHIC_CAMELLIA_ON 1
#endif

/** @brief 启用 AES CCM*-无标签流密码（PSA CCM_STAR_NO_TAG）。 */
#ifndef XCRYPTOGRAPHIC_CCM_STAR_NO_TAG_ON
#define XCRYPTOGRAPHIC_CCM_STAR_NO_TAG_ON 1
#endif

/** @brief 启用 FFDH（RFC 7919 有限域 Diffie-Hellman）密钥协商。 */
#ifndef XCRYPTOGRAPHIC_FFDH_ON
#define XCRYPTOGRAPHIC_FFDH_ON 1
#endif

/** @brief 启用 AES 密钥封装 KW/KWP（RFC 3394/RFC 5649）。 */
#ifndef XCRYPTOGRAPHIC_AES_KEY_WRAP_ON
#define XCRYPTOGRAPHIC_AES_KEY_WRAP_ON 1
#endif


/** @brief 启用 RSA 公钥加密/解密与签名/验签（含 PKCS#1 v1.5、OAEP、PSS）。 */
#ifndef XCRYPTOGRAPHIC_RSA_ON
#define XCRYPTOGRAPHIC_RSA_ON 1
#endif
/** @brief 启用 NIST P-384 ECDH/ECDSA（secp384r1）。 */
#ifndef XCRYPTOGRAPHIC_ECC_SECP384R1_ON
#define XCRYPTOGRAPHIC_ECC_SECP384R1_ON 1
#endif

/** @brief 启用 NIST P-521 ECDH/ECDSA（secp521r1）。 */
#ifndef XCRYPTOGRAPHIC_ECC_SECP521R1_ON
#define XCRYPTOGRAPHIC_ECC_SECP521R1_ON 1
#endif

/** @brief 启用 NIST P-521 ECDSA。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_NISTP521_ON
#define XCRYPTOGRAPHIC_ECDSA_NISTP521_ON XCRYPTOGRAPHIC_ECC_SECP521R1_ON
#endif

/** @brief 启用 NIST P-521 确定性 ECDSA（RFC 6979）。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_NISTP521_ON
#define XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_NISTP521_ON XCRYPTOGRAPHIC_ECDSA_NISTP521_ON
#endif

/** @brief 启用 secp256k1 ECDH/ECDSA。 */
#ifndef XCRYPTOGRAPHIC_ECC_SECP256K1_ON
#define XCRYPTOGRAPHIC_ECC_SECP256K1_ON 1
#endif

/** @brief 启用 brainpoolP256r1 ECDH/ECDSA。 */
#ifndef XCRYPTOGRAPHIC_ECC_BRAINPOOL_P256R1_ON
#define XCRYPTOGRAPHIC_ECC_BRAINPOOL_P256R1_ON 1
#endif

/** @brief 启用 brainpoolP256r1 ECDSA 签名与验签。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_BRAINPOOL_P256R1_ON
#define XCRYPTOGRAPHIC_ECDSA_BRAINPOOL_P256R1_ON XCRYPTOGRAPHIC_ECC_BRAINPOOL_P256R1_ON
#endif

/** @brief 启用 brainpoolP256r1 确定性 ECDSA（RFC 6979）。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_BRAINPOOL_P256R1_ON
#define XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_BRAINPOOL_P256R1_ON \
    XCRYPTOGRAPHIC_ECDSA_BRAINPOOL_P256R1_ON
#endif

/** @brief 启用 brainpoolP384r1 ECDH/ECDSA。 */
#ifndef XCRYPTOGRAPHIC_ECC_BRAINPOOL_P384R1_ON
#define XCRYPTOGRAPHIC_ECC_BRAINPOOL_P384R1_ON 1
#endif

/** @brief 启用 brainpoolP384r1 ECDSA 签名与验签。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_BRAINPOOL_P384R1_ON
#define XCRYPTOGRAPHIC_ECDSA_BRAINPOOL_P384R1_ON XCRYPTOGRAPHIC_ECC_BRAINPOOL_P384R1_ON
#endif

/** @brief 启用 brainpoolP384r1 确定性 ECDSA（RFC 6979）。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_BRAINPOOL_P384R1_ON
#define XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_BRAINPOOL_P384R1_ON \
    XCRYPTOGRAPHIC_ECDSA_BRAINPOOL_P384R1_ON
#endif

/** @brief 启用 brainpoolP512r1 ECDH/ECDSA。 */
#ifndef XCRYPTOGRAPHIC_ECC_BRAINPOOL_P512R1_ON
#define XCRYPTOGRAPHIC_ECC_BRAINPOOL_P512R1_ON 1
#endif

/** @brief 启用 brainpoolP512r1 ECDSA 签名与验签。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_BRAINPOOL_P512R1_ON
#define XCRYPTOGRAPHIC_ECDSA_BRAINPOOL_P512R1_ON XCRYPTOGRAPHIC_ECC_BRAINPOOL_P512R1_ON
#endif

/** @brief 启用 brainpoolP512r1 确定性 ECDSA（RFC 6979）。 */
#ifndef XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_BRAINPOOL_P512R1_ON
#define XCRYPTOGRAPHIC_ECDSA_DETERMINISTIC_BRAINPOOL_P512R1_ON \
    XCRYPTOGRAPHIC_ECDSA_BRAINPOOL_P512R1_ON
#endif

/** @brief 启用 X448（Montgomery）密钥协商。 */
#ifndef XCRYPTOGRAPHIC_X448_ON
#define XCRYPTOGRAPHIC_X448_ON 1
#endif

#endif /* XCRYPTOGRAPHIC_CONFIG_H */
