#include "XGreater.h"
XDefineFunc_ComeTrue(XGreater, > , char)
XDefineFunc_ComeTrueTwo(XGreater, > , unsigned, char)
XDefineFunc_ComeTrue(XGreater, > , int)
XDefineFunc_ComeTrue(XGreater, > , long)
XDefineFunc_ComeTrueTwo(XGreater, > , unsigned, int)
XDefineFunc_ComeTrueTwo(XGreater, > ,  short, int)
XDefineFunc_ComeTrueTwo(XGreater, > ,  long, int)
XDefineFunc_ComeTrueTwo(XGreater, > ,  long, long)
XDefineFunc_ComeTrueTwo(XGreater, > ,  unsigned, long)
XDefineFunc_ComeTrue(XGreater, > , float)
XDefineFunc_ComeTrue(XGreater, > , double)
XDefineFunc_ComeTrueTwo(XGreater, > , long, double)
