#include "XLess.h"
XDefineFunc_ComeTrue(XLess, < , char)
XDefineFunc_ComeTrueTwo(XLess, < , unsigned, char)
XDefineFunc_ComeTrue(XLess, < , int)
XDefineFunc_ComeTrue(XLess, < , long)
XDefineFunc_ComeTrueTwo(XLess, <  , unsigned, int)
XDefineFunc_ComeTrueTwo(XLess, <  , short, int)
XDefineFunc_ComeTrueTwo(XLess, <  , long, int)
XDefineFunc_ComeTrueTwo(XLess, <  , long, long)
XDefineFunc_ComeTrueTwo(XLess, <  , unsigned, long)
XDefineFunc_ComeTrue(XLess, <  , float)
XDefineFunc_ComeTrue(XLess, <  , double)
XDefineFunc_ComeTrueTwo(XLess, < , long, double)

XDefineFunc_XMapComeTrue(XLess, < , char)
XDefineFunc_XMapComeTrueTwo(XLess, < , unsigned, char)
XDefineFunc_XMapComeTrue(XLess, < , int)
XDefineFunc_XMapComeTrue(XLess, < , long)
XDefineFunc_XMapComeTrueTwo(XLess, <  , unsigned, int)
XDefineFunc_XMapComeTrueTwo(XLess, <  , short, int)
XDefineFunc_XMapComeTrueTwo(XLess, <  , long, int)
XDefineFunc_XMapComeTrueTwo(XLess, <  , long, long)
XDefineFunc_XMapComeTrueTwo(XLess, <  , unsigned, long)
XDefineFunc_XMapComeTrue(XLess, <  , float)
XDefineFunc_XMapComeTrue(XLess, <  , double)
XDefineFunc_XMapComeTrueTwo(XLess, < , long, double)
//const bool XLess_int(const void* LPrevValue, const void* LNextValue)
//{
//	return *(int*)LPrevValue < *(int*)LNextValue;
//}
